// Generated by CoffeeScript 1.6.3-reflective
(function() {
  var injectSrc, s, setup;

  injectSrc = chrome.extension.getURL("inject.js");

  setup = function(injectSrc) {
    var h, loadUp;
    loadUp = function() {
      return (function(s) {
        s.id = "coffeeconsoleinject";
        s.src = injectSrc;
        document.body.appendChild(s);
      })(document.createElement("script"));
    };
    h = function(e) {
      if (e.keyCode === 77 && (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)) {
        e.preventDefault();
        return loadUp();
      }
    };
    return document.addEventListener("keydown", h, false);
  };

  s = document.createElement("SCRIPT");

  setup = setup.toString();

  setup = "(" + setup + ")(" + JSON.stringify(injectSrc) + ")";

  s.innerHTML = setup;

  document.body.appendChild(s);

}).call(this);
