// Generated by CoffeeScript 1.4.0
(function() {

  (function(s) {
    s.id = "coffeeconsoleinject";
    s.src = chrome.extension.getURL("inject.js");
    document.body.appendChild(s);
  })(document.createElement("script"));

}).call(this);
